name: iOS CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    name: Build and Test Apollo iOS
    runs-on: macos-latest
    env:
      SCHEME_NAME: Apollo 
      platform: iOS Simulator
      device: iPhone 14

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        
      - name: List Directory Contents
        run: ls -al

      - name: Build
        run: |
          # Checking for .xcworkspace or .xcodeproj
          if [[ -f *.xcworkspace ]]; then 
            filetype_parameter="workspace" 
            file_to_build=$(ls *.xcworkspace)
          elif [[ -f *.xcodeproj ]]; then
            filetype_parameter="project" 
            file_to_build=$(ls *.xcodeproj)
          else
            echo "Neither .xcworkspace nor .xcodeproj found!"
            exit 1
          fi

          xcodebuild build-for-testing -scheme "$SCHEME_NAME" -"$filetype_parameter" "$file_to_build" -destination "platform=$platform,name=$device"

      - name: Test
        run: |
          # Re-using the detection mechanism for .xcworkspace or .xcodeproj
          if [[ -f *.xcworkspace ]]; then 
            filetype_parameter="workspace" 
            file_to_build=$(ls *.xcworkspace)
          elif [[ -f *.xcodeproj ]]; then
            filetype_parameter="project" 
            file_to_build=$(ls *.xcodeproj)
          else
            echo "Neither .xcworkspace nor .xcodeproj found!"
            exit 1
          fi

          xcodebuild test-without-building -scheme "$SCHEME_NAME" -"$filetype_parameter" "$file_to_build" -destination "platform=$platform,name=$device"
