name: iOS CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    name: Build and Test Apollo iOS
    runs-on: macos-latest
    env:
      SCHEME_NAME: Apollo 
      platform: iOS Simulator
      device: iPhone 14

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        
      - name: List Directory Contents
        run: ls -al

      - name: Build
        run: |
          file_to_build="Apollo.xcodeproj"
          filetype_parameter="project"
          
          # Ensure the file exists, just as an extra check
          if [[ ! -f $file_to_build ]]; then
            echo "$file_to_build not found!"
            exit 1
          fi

          xcodebuild build-for-testing -scheme "$SCHEME_NAME" -"$filetype_parameter" "$file_to_build" -destination "platform=$platform,name=$device"

      - name: Test
        run: |
          file_to_build="Apollo.xcodeproj"
          filetype_parameter="project"

          # Ensure the file exists, just as an extra check
          if [[ ! -f $file_to_build ]]; then
            echo "$file_to_build not found!"
            exit 1
          fi

          xcodebuild test-without-building -scheme "$SCHEME_NAME" -"$filetype_parameter" "$file_to_build" -destination "platform=$platform,name=$device"
